name: Draft PDF

on:
  push:
    paths:
      - joss/**
      - .github/workflows/draft_pdf.yml

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: TeX and PDF
        uses: docker://openjournals/paperdraft:latest
        with:
          args: '-k joss/paper.md'
        env:
          GIT_SHA: $GITHUB_SHA
          JOURNAL: joss
      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: paper
          path: joss/